import { business, services, portfolio, faqs } from './data.mjs';
export const esc = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const arrow = '<span aria-hidden="true">↗</span>';
export const link = (text, href, type = 'primary') => `<a class="button button-${type}" href="${href}">${text}${arrow}</a>`;
export const eyebrow = text => `<p class="eyebrow">${text}</p>`;
export const image = (src, alt, cls = '', eager = false, position = 'center') => `<img class="${cls}" src="${src}&w=900&q=82" srcset="${src}&w=480&q=80 480w, ${src}&w=900&q=82 900w, ${src}&w=1500&q=85 1500w" sizes="${cls === 'hero-photo' ? '(max-width: 760px) 100vw, 58vw' : '(max-width: 600px) 90vw, (max-width: 1000px) 50vw, 33vw'}" alt="${esc(alt)}" width="900" height="1200" loading="${eager ? 'eager' : 'lazy'}" ${eager ? 'fetchpriority="high"' : ''} decoding="async" style="object-position:${position}">`;
const navItems = [['home', 'Home'], ['services', 'Services'], ['portfolio', 'Portfolio'], ['about', 'About'], ['new-clients', 'New Clients'], ['contact', 'Contact']];
export const pageHref = page => page === 'home' ? './index.html' : `./${page}.html`;
export function header(page) { return `<a class="skip-link" href="#main">Skip to content</a><div class="announcement">A little time for yourself. A beautiful difference. <span>Now welcoming new clients ${arrow}</span></div><header class="site-header"><nav class="container nav" aria-label="Main navigation"><a class="brand" href="./index.html" aria-label="Gladys Cosmetology Studio home"><span class="brand-name">gladys<span class="brand-dot">.</span></span><span class="brand-sub">COSMETOLOGY STUDIO</span></a><div class="desktop-nav">${navItems.map(([id, title]) => `<a href="${pageHref(id)}" ${page === id ? 'aria-current="page"' : ''}>${title}</a>`).join('')}</div><div class="nav-actions">${link('Book Now', './book.html')}<button class="menu-toggle" aria-controls="mobile-nav" aria-expanded="false" aria-label="Open navigation"><span></span><span></span></button></div><div id="mobile-nav" class="mobile-nav" hidden>${navItems.map(([id, title]) => `<a href="${pageHref(id)}" ${page === id ? 'aria-current="page"' : ''}>${title}${arrow}</a>`).join('')}${link('Book an Appointment', './book.html')}</div></nav></header>`; }
export function footer() { return `<footer class="site-footer"><div class="container footer-grid"><div><a class="brand" href="./index.html"><span class="brand-name">gladys<span class="brand-dot">.</span></span><span class="brand-sub">COSMETOLOGY STUDIO</span></a><p>Healthy hair. Effortless style.<br>Always, authentically you.</p><a class="text-link" href="${business.instagram}" target="_blank" rel="noopener noreferrer">${business.handle} ${arrow}</a></div><div><h2 class="footer-heading">EXPLORE</h2><a href="./services.html">Services</a><a href="./portfolio.html">Portfolio</a><a href="./about.html">Meet Gladys</a></div><div><h2 class="footer-heading">YOUR VISIT</h2><a href="./new-clients.html">New clients</a><a href="./new-clients.html#faq">Policies & FAQ</a><a href="./contact.html">Find the studio</a></div><div><h2 class="footer-heading">LET’S MAKE TIME FOR YOU</h2><p>A thoughtful consultation.<br>A look you’ll love living in.</p>${link('Book Your Appointment', './book.html', 'outline')}</div></div><div class="container footer-bottom"><span>© ${new Date().getFullYear()} ${business.name}</span><span>Made with care. Styled with intention.</span></div></footer><div class="mobile-booking"><span>Your next good hair day.</span>${link('Book Now', './book.html')}</div>`; }
export function sectionHeading(kicker, title, action = '') { return `<div class="section-heading"><div>${eyebrow(kicker)}<h2>${title}</h2></div>${action}</div>`; }
export function portfolioCard(item, index = 0) { return `<button class="portfolio-card ${item.tall ? 'is-tall' : ''}" data-lightbox="${item.id}" aria-label="View ${esc(item.title)}"><span class="portfolio-image">${image(item.image, item.alt, '', false, item.position)}<span class="image-open" aria-hidden="true">↗</span></span><span class="portfolio-caption"><span>${item.title}</span><span>${item.category}</span></span></button>`; }
export function serviceCard(service, index) { return `<article class="service-card"><div class="service-top"><span class="service-number">0${index + 1}</span><span>${service.duration}</span></div><h3>${service.shortName}</h3><p>${service.description}</p><div class="service-bottom"><span>Starting at <strong>$${service.price}</strong></span><a href="./book.html?service=${service.consultation ? 'consultation' : service.id}" aria-label="${service.consultation ? 'Book an extensions consultation' : `Book ${service.shortName}`}">${service.consultation ? 'Book a Consultation' : 'Book This Service'} ${arrow}</a></div></article>`; }
export function finalCta() { return `<section class="final-cta"><div class="container">${eyebrow('YOUR NEXT CHAPTER, BEAUTIFULLY STYLED')}<h2>Ready for your <em>next look?</em></h2><p>Let’s create something that feels a little more like you.</p>${link('Book Your Appointment', './book.html', 'light')}<span class="cta-note">One stylist. Your undivided attention.</span></div></section>`; }
export function faqList() { return `<div class="faq-list">${faqs.map(([q, a]) => `<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div>`; }
export function lightbox() { return `<dialog class="lightbox" aria-labelledby="lightbox-title"><button class="lightbox-close icon-button" aria-label="Close image">×</button><div class="lightbox-stage"><button class="lightbox-prev icon-button" aria-label="Previous image">←</button><img id="lightbox-image" alt=""><button class="lightbox-next icon-button" aria-label="Next image">→</button></div><div class="lightbox-caption"><h2 id="lightbox-title"></h2><p id="lightbox-category"></p><p class="fine-print">Inspiration photography · Replace with Gladys’s client work.</p></div></dialog>`; }
